/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FileRenameFilesRequestUpdatesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FileUpdateFileNameRequest
 */
public class FileUpdateFileNameRequestTest {
    private final FileUpdateFileNameRequest model = new FileUpdateFileNameRequest();

    /**
     * Model tests for FileUpdateFileNameRequest
     */
    @Test
    public void testFileUpdateFileNameRequest() {
        // TODO: test FileUpdateFileNameRequest
    }

    /**
     * Test the property 'updates'
     */
    @Test
    public void updatesTest() {
        // TODO: test updates
    }

}
