/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PresignedPostURLs
 */
public class PresignedPostURLsTest {
    private final PresignedPostURLs model = new PresignedPostURLs();

    /**
     * Model tests for PresignedPostURLs
     */
    @Test
    public void testPresignedPostURLs() {
        // TODO: test PresignedPostURLs
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'fileType'
     */
    @Test
    public void fileTypeTest() {
        // TODO: test fileType
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    public void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'contentDisposition'
     */
    @Test
    public void contentDispositionTest() {
        // TODO: test contentDisposition
    }

    /**
     * Test the property 'pollingJwt'
     */
    @Test
    public void pollingJwtTest() {
        // TODO: test pollingJwt
    }

    /**
     * Test the property 'pollingUrl'
     */
    @Test
    public void pollingUrlTest() {
        // TODO: test pollingUrl
    }

    /**
     * Test the property 'customId'
     */
    @Test
    public void customIdTest() {
        // TODO: test customId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'urls'
     */
    @Test
    public void urlsTest() {
        // TODO: test urls
    }

    /**
     * Test the property 'uploadId'
     */
    @Test
    public void uploadIdTest() {
        // TODO: test uploadId
    }

    /**
     * Test the property 'chunkSize'
     */
    @Test
    public void chunkSizeTest() {
        // TODO: test chunkSize
    }

    /**
     * Test the property 'chunkCount'
     */
    @Test
    public void chunkCountTest() {
        // TODO: test chunkCount
    }

}
