/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * FileListFilesRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FileListFilesRequest {
  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private Double limit = 500d;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private Double offset = 0d;

  public FileListFilesRequest() {
  }

  public FileListFilesRequest limit(Double limit) {
    if (limit != null && limit < 0) {
      throw new IllegalArgumentException("Invalid value for limit. Must be greater than or equal to 0.");
    }
    if (limit != null && limit > 100000) {
      throw new IllegalArgumentException("Invalid value for limit. Must be less than or equal to 100000.");
    }
    
    
    this.limit = limit;
    return this;
  }

  public FileListFilesRequest limit(Integer limit) {
    if (limit != null && limit < 0) {
      throw new IllegalArgumentException("Invalid value for limit. Must be greater than or equal to 0.");
    }
    if (limit != null && limit > 100000) {
      throw new IllegalArgumentException("Invalid value for limit. Must be less than or equal to 100000.");
    }
    
    
    this.limit = limit.doubleValue();
    return this;
  }

   /**
   * The maximum number of files to retrieve.
   * minimum: 0
   * maximum: 100000
   * @return limit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "500", required = true, value = "The maximum number of files to retrieve.")

  public Double getLimit() {
    return limit;
  }


  public void setLimit(Double limit) {
    if (limit != null && limit < 0) {
      throw new IllegalArgumentException("Invalid value for limit. Must be greater than or equal to 0.");
    }
    if (limit != null && limit > 100000) {
      throw new IllegalArgumentException("Invalid value for limit. Must be less than or equal to 100000.");
    }
    
    this.limit = limit;
  }


  public FileListFilesRequest offset(Double offset) {
    if (offset != null && offset < 0) {
      throw new IllegalArgumentException("Invalid value for offset. Must be greater than or equal to 0.");
    }
    
    
    
    this.offset = offset;
    return this;
  }

  public FileListFilesRequest offset(Integer offset) {
    if (offset != null && offset < 0) {
      throw new IllegalArgumentException("Invalid value for offset. Must be greater than or equal to 0.");
    }
    
    
    
    this.offset = offset.doubleValue();
    return this;
  }

   /**
   * The number of files to skip.
   * minimum: 0
   * @return offset
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "The number of files to skip.")

  public Double getOffset() {
    return offset;
  }


  public void setOffset(Double offset) {
    if (offset != null && offset < 0) {
      throw new IllegalArgumentException("Invalid value for offset. Must be greater than or equal to 0.");
    }
    
    
    this.offset = offset;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FileListFilesRequest instance itself
   */
  public FileListFilesRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileListFilesRequest fileListFilesRequest = (FileListFilesRequest) o;
    return Objects.equals(this.limit, fileListFilesRequest.limit) &&
        Objects.equals(this.offset, fileListFilesRequest.offset)&&
        Objects.equals(this.additionalProperties, fileListFilesRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, offset, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileListFilesRequest {\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("limit");
    openapiFields.add("offset");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("limit");
    openapiRequiredFields.add("offset");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FileListFilesRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FileListFilesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FileListFilesRequest is not found in the empty JSON string", FileListFilesRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FileListFilesRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileListFilesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileListFilesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileListFilesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileListFilesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<FileListFilesRequest>() {
           @Override
           public void write(JsonWriter out, FileListFilesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FileListFilesRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FileListFilesRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FileListFilesRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FileListFilesRequest
  * @throws IOException if the JSON string is invalid with respect to FileListFilesRequest
  */
  public static FileListFilesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileListFilesRequest.class);
  }

 /**
  * Convert an instance of FileListFilesRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

