/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UploadRequestPresignedUrlsRequestFilesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UploadRequestPresignedUrlsRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UploadRequestPresignedUrlsRequest {
  public static final String SERIALIZED_NAME_CALLBACK_URL = "callbackUrl";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  private URI callbackUrl;

  public static final String SERIALIZED_NAME_CALLBACK_SLUG = "callbackSlug";
  @SerializedName(SERIALIZED_NAME_CALLBACK_SLUG)
  private String callbackSlug;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<UploadRequestPresignedUrlsRequestFilesInner> files = new ArrayList<>();

  public static final String SERIALIZED_NAME_ROUTE_CONFIG = "routeConfig";
  @SerializedName(SERIALIZED_NAME_ROUTE_CONFIG)
  private Object routeConfig = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata = null;

  public UploadRequestPresignedUrlsRequest() {
  }

  public UploadRequestPresignedUrlsRequest callbackUrl(URI callbackUrl) {
    
    
    
    
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getCallbackUrl() {
    return callbackUrl;
  }


  public void setCallbackUrl(URI callbackUrl) {
    
    
    
    this.callbackUrl = callbackUrl;
  }


  public UploadRequestPresignedUrlsRequest callbackSlug(String callbackSlug) {
    
    
    
    
    this.callbackSlug = callbackSlug;
    return this;
  }

   /**
   * Get callbackSlug
   * @return callbackSlug
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCallbackSlug() {
    return callbackSlug;
  }


  public void setCallbackSlug(String callbackSlug) {
    
    
    
    this.callbackSlug = callbackSlug;
  }


  public UploadRequestPresignedUrlsRequest files(List<UploadRequestPresignedUrlsRequestFilesInner> files) {
    
    
    
    
    this.files = files;
    return this;
  }

  public UploadRequestPresignedUrlsRequest addFilesItem(UploadRequestPresignedUrlsRequestFilesInner filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<UploadRequestPresignedUrlsRequestFilesInner> getFiles() {
    return files;
  }


  public void setFiles(List<UploadRequestPresignedUrlsRequestFilesInner> files) {
    
    
    
    this.files = files;
  }


  public UploadRequestPresignedUrlsRequest routeConfig(Object routeConfig) {
    
    
    
    
    this.routeConfig = routeConfig;
    return this;
  }

   /**
   * Get routeConfig
   * @return routeConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getRouteConfig() {
    return routeConfig;
  }


  public void setRouteConfig(Object routeConfig) {
    
    
    
    this.routeConfig = routeConfig;
  }


  public UploadRequestPresignedUrlsRequest metadata(Object metadata) {
    
    
    
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    
    
    
    this.metadata = metadata;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UploadRequestPresignedUrlsRequest instance itself
   */
  public UploadRequestPresignedUrlsRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UploadRequestPresignedUrlsRequest uploadRequestPresignedUrlsRequest = (UploadRequestPresignedUrlsRequest) o;
    return Objects.equals(this.callbackUrl, uploadRequestPresignedUrlsRequest.callbackUrl) &&
        Objects.equals(this.callbackSlug, uploadRequestPresignedUrlsRequest.callbackSlug) &&
        Objects.equals(this.files, uploadRequestPresignedUrlsRequest.files) &&
        Objects.equals(this.routeConfig, uploadRequestPresignedUrlsRequest.routeConfig) &&
        Objects.equals(this.metadata, uploadRequestPresignedUrlsRequest.metadata)&&
        Objects.equals(this.additionalProperties, uploadRequestPresignedUrlsRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, callbackSlug, files, routeConfig, metadata, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadRequestPresignedUrlsRequest {\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    callbackSlug: ").append(toIndentedString(callbackSlug)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    routeConfig: ").append(toIndentedString(routeConfig)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("callbackUrl");
    openapiFields.add("callbackSlug");
    openapiFields.add("files");
    openapiFields.add("routeConfig");
    openapiFields.add("metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("callbackUrl");
    openapiRequiredFields.add("callbackSlug");
    openapiRequiredFields.add("files");
    openapiRequiredFields.add("routeConfig");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UploadRequestPresignedUrlsRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UploadRequestPresignedUrlsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UploadRequestPresignedUrlsRequest is not found in the empty JSON string", UploadRequestPresignedUrlsRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UploadRequestPresignedUrlsRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("callbackUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `callbackUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callbackUrl").toString()));
      }
      if (!jsonObj.get("callbackSlug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `callbackSlug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callbackSlug").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("files").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
      }

      JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
      // validate the required field `files` (array)
      for (int i = 0; i < jsonArrayfiles.size(); i++) {
        UploadRequestPresignedUrlsRequestFilesInner.validateJsonObject(jsonArrayfiles.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UploadRequestPresignedUrlsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UploadRequestPresignedUrlsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UploadRequestPresignedUrlsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UploadRequestPresignedUrlsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UploadRequestPresignedUrlsRequest>() {
           @Override
           public void write(JsonWriter out, UploadRequestPresignedUrlsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UploadRequestPresignedUrlsRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UploadRequestPresignedUrlsRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UploadRequestPresignedUrlsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UploadRequestPresignedUrlsRequest
  * @throws IOException if the JSON string is invalid with respect to UploadRequestPresignedUrlsRequest
  */
  public static UploadRequestPresignedUrlsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UploadRequestPresignedUrlsRequest.class);
  }

 /**
  * Convert an instance of UploadRequestPresignedUrlsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

