/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CallbackMarkUploadFailedRequest;
import com.konfigthis.client.model.CallbackMarkUploadFailedResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CallbackApi
 */
@Disabled
public class CallbackApiTest {

    private static CallbackApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CallbackApi(apiClient);
    }

    /**
     * Mark an upload as failed, or abort a multipart upload. This will free up resources and revert the storage quota.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void markUploadFailedTest() throws ApiException {
        String fileKey = null;
        String xUploadthingVersion = null;
        String uploadId = null;
        String xUploadthingFePackage = null;
        String xUploadthingBeAdapter = null;
        CallbackMarkUploadFailedResponse response = api.markUploadFailed(fileKey, xUploadthingVersion)
                .uploadId(uploadId)
                .xUploadthingFePackage(xUploadthingFePackage)
                .xUploadthingBeAdapter(xUploadthingBeAdapter)
                .execute();
        // TODO: test validations
    }

}
