/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.MultipartCompleteUploadRequest;
import com.konfigthis.client.model.MultipartCompleteUploadRequestEtagsInner;
import com.konfigthis.client.model.MultipartCompleteUploadResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MultipartApi
 */
@Disabled
public class MultipartApiTest {

    private static MultipartApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MultipartApi(apiClient);
    }

    /**
     * Complete a multipart upload. This will finalize the upload and make the file available for download.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void completeUploadTest() throws ApiException {
        String fileKey = null;
        String uploadId = null;
        List<MultipartCompleteUploadRequestEtagsInner> etags = null;
        String xUploadthingVersion = null;
        String xUploadthingFePackage = null;
        String xUploadthingBeAdapter = null;
        MultipartCompleteUploadResponse response = api.completeUpload(fileKey, uploadId, etags, xUploadthingVersion)
                .xUploadthingFePackage(xUploadthingFePackage)
                .xUploadthingBeAdapter(xUploadthingBeAdapter)
                .execute();
        // TODO: test validations
    }

}
