/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.net.URI;
import com.konfigthis.client.model.UploadRequestPresignedUrlsRequest;
import com.konfigthis.client.model.UploadRequestPresignedUrlsRequestFilesInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadApi
 */
@Disabled
public class UploadApiTest {

    private static UploadApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new UploadApi(apiClient);
    }

    /**
     * Request presigned URLs for file uploads through based on your file router. NOTE: This spec complies with SDK versions ^6.4. Response may vary for older versions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestPresignedUrlsTest() throws ApiException {
        URI callbackUrl = null;
        String callbackSlug = null;
        List<UploadRequestPresignedUrlsRequestFilesInner> files = null;
        Object routeConfig = null;
        String xUploadthingVersion = null;
        Object metadata = null;
        String xUploadthingFePackage = null;
        String xUploadthingBeAdapter = null;
        List<Object> response = api.requestPresignedUrls(callbackUrl, callbackSlug, files, routeConfig, xUploadthingVersion)
                .metadata(metadata)
                .xUploadthingFePackage(xUploadthingFePackage)
                .xUploadthingBeAdapter(xUploadthingBeAdapter)
                .execute();
        // TODO: test validations
    }

}
