/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.MultipartCompleteUploadRequest;
import com.konfigthis.client.model.MultipartCompleteUploadRequestEtagsInner;
import com.konfigthis.client.model.MultipartCompleteUploadResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class MultipartApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MultipartApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public MultipartApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKeyAuth() == null) {
            throw new IllegalArgumentException("\"x-uploadthing-api-key\" is required but no API key was provided. Please set \"x-uploadthing-api-key\" with ApiClient#setApiKeyAuth(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call completeUploadCall(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, MultipartCompleteUploadRequest multipartCompleteUploadRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = multipartCompleteUploadRequest;

        // create path and map variables
        String localVarPath = "/completeMultipart";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (xUploadthingVersion != null) {
            localVarHeaderParams.put("x-uploadthing-version", localVarApiClient.parameterToString(xUploadthingVersion));
        }

        if (xUploadthingFePackage != null) {
            localVarHeaderParams.put("x-uploadthing-fe-package", localVarApiClient.parameterToString(xUploadthingFePackage));
        }

        if (xUploadthingBeAdapter != null) {
            localVarHeaderParams.put("x-uploadthing-be-adapter", localVarApiClient.parameterToString(xUploadthingBeAdapter));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call completeUploadValidateBeforeCall(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, MultipartCompleteUploadRequest multipartCompleteUploadRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xUploadthingVersion' is set
        if (xUploadthingVersion == null) {
            throw new ApiException("Missing the required parameter 'xUploadthingVersion' when calling completeUpload(Async)");
        }

        return completeUploadCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest, _callback);

    }


    private ApiResponse<MultipartCompleteUploadResponse> completeUploadWithHttpInfo(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, MultipartCompleteUploadRequest multipartCompleteUploadRequest) throws ApiException {
        okhttp3.Call localVarCall = completeUploadValidateBeforeCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest, null);
        Type localVarReturnType = new TypeToken<MultipartCompleteUploadResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call completeUploadAsync(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, MultipartCompleteUploadRequest multipartCompleteUploadRequest, final ApiCallback<MultipartCompleteUploadResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = completeUploadValidateBeforeCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest, _callback);
        Type localVarReturnType = new TypeToken<MultipartCompleteUploadResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CompleteUploadRequestBuilder {
        private final String fileKey;
        private final String uploadId;
        private final List<MultipartCompleteUploadRequestEtagsInner> etags;
        private final String xUploadthingVersion;
        private String xUploadthingFePackage;
        private String xUploadthingBeAdapter;

        private CompleteUploadRequestBuilder(String fileKey, String uploadId, List<MultipartCompleteUploadRequestEtagsInner> etags, String xUploadthingVersion) {
            this.fileKey = fileKey;
            this.uploadId = uploadId;
            this.etags = etags;
            this.xUploadthingVersion = xUploadthingVersion;
        }

        /**
         * Set xUploadthingFePackage
         * @param xUploadthingFePackage  (optional)
         * @return CompleteUploadRequestBuilder
         */
        public CompleteUploadRequestBuilder xUploadthingFePackage(String xUploadthingFePackage) {
            this.xUploadthingFePackage = xUploadthingFePackage;
            return this;
        }
        
        /**
         * Set xUploadthingBeAdapter
         * @param xUploadthingBeAdapter  (optional)
         * @return CompleteUploadRequestBuilder
         */
        public CompleteUploadRequestBuilder xUploadthingBeAdapter(String xUploadthingBeAdapter) {
            this.xUploadthingBeAdapter = xUploadthingBeAdapter;
            return this;
        }
        
        /**
         * Build call for completeUpload
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully completed the multipart upload. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            MultipartCompleteUploadRequest multipartCompleteUploadRequest = buildBodyParams();
            return completeUploadCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest, _callback);
        }

        private MultipartCompleteUploadRequest buildBodyParams() {
            MultipartCompleteUploadRequest multipartCompleteUploadRequest = new MultipartCompleteUploadRequest();
            multipartCompleteUploadRequest.fileKey(this.fileKey);
            multipartCompleteUploadRequest.uploadId(this.uploadId);
            multipartCompleteUploadRequest.etags(this.etags);
            return multipartCompleteUploadRequest;
        }

        /**
         * Execute completeUpload request
         * @return MultipartCompleteUploadResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully completed the multipart upload. </td><td>  -  </td></tr>
         </table>
         */
        public MultipartCompleteUploadResponse execute() throws ApiException {
            MultipartCompleteUploadRequest multipartCompleteUploadRequest = buildBodyParams();
            ApiResponse<MultipartCompleteUploadResponse> localVarResp = completeUploadWithHttpInfo(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute completeUpload request with HTTP info returned
         * @return ApiResponse&lt;MultipartCompleteUploadResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully completed the multipart upload. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<MultipartCompleteUploadResponse> executeWithHttpInfo() throws ApiException {
            MultipartCompleteUploadRequest multipartCompleteUploadRequest = buildBodyParams();
            return completeUploadWithHttpInfo(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest);
        }

        /**
         * Execute completeUpload request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully completed the multipart upload. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<MultipartCompleteUploadResponse> _callback) throws ApiException {
            MultipartCompleteUploadRequest multipartCompleteUploadRequest = buildBodyParams();
            return completeUploadAsync(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, multipartCompleteUploadRequest, _callback);
        }
    }

    /**
     * 
     * Complete a multipart upload. This will finalize the upload and make the file available for download.
     * @param xUploadthingVersion  (required)
     * @return CompleteUploadRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully completed the multipart upload. </td><td>  -  </td></tr>
     </table>
     */
    public CompleteUploadRequestBuilder completeUpload(String fileKey, String uploadId, List<MultipartCompleteUploadRequestEtagsInner> etags, String xUploadthingVersion) throws IllegalArgumentException {
        if (fileKey == null) throw new IllegalArgumentException("\"fileKey\" is required but got null");
            

        if (uploadId == null) throw new IllegalArgumentException("\"uploadId\" is required but got null");
            

        if (etags == null) throw new IllegalArgumentException("\"etags\" is required but got null");
        if (xUploadthingVersion == null) throw new IllegalArgumentException("\"xUploadthingVersion\" is required but got null");
            

        return new CompleteUploadRequestBuilder(fileKey, uploadId, etags, xUploadthingVersion);
    }
}
