/*
 * UploadThing REST API
 * UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.
 *
 * The version of the OpenAPI document: 6.4.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.ServerCallbackGetDataResponse;
import com.konfigthis.client.model.ServerCallbackSetDataRequest;
import com.konfigthis.client.model.ServerCallbackSetDataResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class ServerCallbackApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ServerCallbackApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public ServerCallbackApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKeyAuth() == null) {
            throw new IllegalArgumentException("\"x-uploadthing-api-key\" is required but no API key was provided. Please set \"x-uploadthing-api-key\" with ApiClient#setApiKeyAuth(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getDataCall(String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serverCallback";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getDataValidateBeforeCall(String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authorization' is set
        if (authorization == null) {
            throw new ApiException("Missing the required parameter 'authorization' when calling getData(Async)");
        }

        return getDataCall(authorization, _callback);

    }


    private ApiResponse<ServerCallbackGetDataResponse> getDataWithHttpInfo(String authorization) throws ApiException {
        okhttp3.Call localVarCall = getDataValidateBeforeCall(authorization, null);
        Type localVarReturnType = new TypeToken<ServerCallbackGetDataResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getDataAsync(String authorization, final ApiCallback<ServerCallbackGetDataResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getDataValidateBeforeCall(authorization, _callback);
        Type localVarReturnType = new TypeToken<ServerCallbackGetDataResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetDataRequestBuilder {
        private final String authorization;

        private GetDataRequestBuilder(String authorization) {
            this.authorization = authorization;
        }

        /**
         * Build call for getData
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Poll successful </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getDataCall(authorization, _callback);
        }


        /**
         * Execute getData request
         * @return ServerCallbackGetDataResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Poll successful </td><td>  -  </td></tr>
         </table>
         */
        public ServerCallbackGetDataResponse execute() throws ApiException {
            ApiResponse<ServerCallbackGetDataResponse> localVarResp = getDataWithHttpInfo(authorization);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getData request with HTTP info returned
         * @return ApiResponse&lt;ServerCallbackGetDataResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Poll successful </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ServerCallbackGetDataResponse> executeWithHttpInfo() throws ApiException {
            return getDataWithHttpInfo(authorization);
        }

        /**
         * Execute getData request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Poll successful </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ServerCallbackGetDataResponse> _callback) throws ApiException {
            return getDataAsync(authorization, _callback);
        }
    }

    /**
     * 
     * Poll for server callback data. This is used to retrieve the data returned from &#x60;onUploadComplete&#x60; callback.
     * @param authorization  (required)
     * @return GetDataRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Poll successful </td><td>  -  </td></tr>
     </table>
     */
    public GetDataRequestBuilder getData(String authorization) throws IllegalArgumentException {
        if (authorization == null) throw new IllegalArgumentException("\"authorization\" is required but got null");
            

        return new GetDataRequestBuilder(authorization);
    }
    private okhttp3.Call setDataCall(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, ServerCallbackSetDataRequest serverCallbackSetDataRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = serverCallbackSetDataRequest;

        // create path and map variables
        String localVarPath = "/serverCallback";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (xUploadthingVersion != null) {
            localVarHeaderParams.put("x-uploadthing-version", localVarApiClient.parameterToString(xUploadthingVersion));
        }

        if (xUploadthingFePackage != null) {
            localVarHeaderParams.put("x-uploadthing-fe-package", localVarApiClient.parameterToString(xUploadthingFePackage));
        }

        if (xUploadthingBeAdapter != null) {
            localVarHeaderParams.put("x-uploadthing-be-adapter", localVarApiClient.parameterToString(xUploadthingBeAdapter));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call setDataValidateBeforeCall(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, ServerCallbackSetDataRequest serverCallbackSetDataRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xUploadthingVersion' is set
        if (xUploadthingVersion == null) {
            throw new ApiException("Missing the required parameter 'xUploadthingVersion' when calling setData(Async)");
        }

        return setDataCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest, _callback);

    }


    private ApiResponse<ServerCallbackSetDataResponse> setDataWithHttpInfo(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, ServerCallbackSetDataRequest serverCallbackSetDataRequest) throws ApiException {
        okhttp3.Call localVarCall = setDataValidateBeforeCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest, null);
        Type localVarReturnType = new TypeToken<ServerCallbackSetDataResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call setDataAsync(String xUploadthingVersion, String xUploadthingFePackage, String xUploadthingBeAdapter, ServerCallbackSetDataRequest serverCallbackSetDataRequest, final ApiCallback<ServerCallbackSetDataResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = setDataValidateBeforeCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest, _callback);
        Type localVarReturnType = new TypeToken<ServerCallbackSetDataResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class SetDataRequestBuilder {
        private final String fileKey;
        private final String xUploadthingVersion;
        private Object callbackData;
        private String xUploadthingFePackage;
        private String xUploadthingBeAdapter;

        private SetDataRequestBuilder(String fileKey, String xUploadthingVersion) {
            this.fileKey = fileKey;
            this.xUploadthingVersion = xUploadthingVersion;
        }

        /**
         * Set callbackData
         * @param callbackData  (optional)
         * @return SetDataRequestBuilder
         */
        public SetDataRequestBuilder callbackData(Object callbackData) {
            this.callbackData = callbackData;
            return this;
        }
        
        /**
         * Set xUploadthingFePackage
         * @param xUploadthingFePackage  (optional)
         * @return SetDataRequestBuilder
         */
        public SetDataRequestBuilder xUploadthingFePackage(String xUploadthingFePackage) {
            this.xUploadthingFePackage = xUploadthingFePackage;
            return this;
        }
        
        /**
         * Set xUploadthingBeAdapter
         * @param xUploadthingBeAdapter  (optional)
         * @return SetDataRequestBuilder
         */
        public SetDataRequestBuilder xUploadthingBeAdapter(String xUploadthingBeAdapter) {
            this.xUploadthingBeAdapter = xUploadthingBeAdapter;
            return this;
        }
        
        /**
         * Build call for setData
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully set callback data. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            ServerCallbackSetDataRequest serverCallbackSetDataRequest = buildBodyParams();
            return setDataCall(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest, _callback);
        }

        private ServerCallbackSetDataRequest buildBodyParams() {
            ServerCallbackSetDataRequest serverCallbackSetDataRequest = new ServerCallbackSetDataRequest();
            serverCallbackSetDataRequest.fileKey(this.fileKey);
            serverCallbackSetDataRequest.callbackData(this.callbackData);
            return serverCallbackSetDataRequest;
        }

        /**
         * Execute setData request
         * @return ServerCallbackSetDataResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully set callback data. </td><td>  -  </td></tr>
         </table>
         */
        public ServerCallbackSetDataResponse execute() throws ApiException {
            ServerCallbackSetDataRequest serverCallbackSetDataRequest = buildBodyParams();
            ApiResponse<ServerCallbackSetDataResponse> localVarResp = setDataWithHttpInfo(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute setData request with HTTP info returned
         * @return ApiResponse&lt;ServerCallbackSetDataResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully set callback data. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ServerCallbackSetDataResponse> executeWithHttpInfo() throws ApiException {
            ServerCallbackSetDataRequest serverCallbackSetDataRequest = buildBodyParams();
            return setDataWithHttpInfo(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest);
        }

        /**
         * Execute setData request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successfully set callback data. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ServerCallbackSetDataResponse> _callback) throws ApiException {
            ServerCallbackSetDataRequest serverCallbackSetDataRequest = buildBodyParams();
            return setDataAsync(xUploadthingVersion, xUploadthingFePackage, xUploadthingBeAdapter, serverCallbackSetDataRequest, _callback);
        }
    }

    /**
     * 
     * Set server callback data. This is used to set the data returned from &#x60;onUploadComplete&#x60; callback.
     * @param xUploadthingVersion  (required)
     * @return SetDataRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully set callback data. </td><td>  -  </td></tr>
     </table>
     */
    public SetDataRequestBuilder setData(String fileKey, String xUploadthingVersion) throws IllegalArgumentException {
        if (fileKey == null) throw new IllegalArgumentException("\"fileKey\" is required but got null");
            

        if (xUploadthingVersion == null) throw new IllegalArgumentException("\"xUploadthingVersion\" is required but got null");
            

        return new SetDataRequestBuilder(fileKey, xUploadthingVersion);
    }
}
